# Multi-stage Dockerfile for Next.js apps
# Optimized for clerk-stripe-starter

# Build stage
FROM node:18-alpine AS builder
WORKDIR /app

# Accept build arguments for environment variables
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG STRIPE_SECRET_KEY
ARG TURSO_DATABASE_URL
ARG TURSO_AUTH_TOKEN
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_YEARLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_YEARLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_YEARLY

# Set environment variables from build args
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV TURSO_DATABASE_URL=$TURSO_DATABASE_URL
ENV TURSO_AUTH_TOKEN=$TURSO_AUTH_TOKEN
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_STARTER_YEARLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_PRO_YEARLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_ID_ENTERPRISE_YEARLY

# Copy package files
COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .

# Build the application
# The output will be in .next/standalone by default with Next.js 13+
RUN npm run build

# Production stage
FROM node:18-alpine AS runner
WORKDIR /app

# Add non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Copy built application
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set permissions
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production

CMD ["node", "server.js"]