[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "Clerk publishable key"
  CLERK_SECRET_KEY = "Clerk secret key"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "Stripe publishable key"
  STRIPE_SECRET_KEY = "Stripe secret key"
  TURSO_DATABASE_URL = "Turso database URL"
  TURSO_AUTH_TOKEN = "Turso auth token"
  CRON_SECRET = "Cron secret"